# Generated by Django 3.2.5 on 2021-08-12 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('floor_no', models.IntegerField()),
                ('type', models.CharField(choices=[('common', 'Common'), ('luxury', 'Luxury')], default='common', max_length=10)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('num_of_adults', models.IntegerField()),
                ('num_of_beds', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('photo_main', models.ImageField(upload_to='photos/rooms/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/rooms/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/rooms/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/rooms/')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
